# Week 03. Naive Bayes Classfier

과제는 총 5개의 cell을 채워주셔야합니다

1~4 문제는 영상과 실습자료에 나와있는 것들을 적절히 응용하시면 됩니다

마지막 5번의 경우 본인의 생각을 마크다운으로 작성하는 부분입니다

주석의 경우 이미지, 테이블 등의 표현이 어려운 관계로 받지 않겠습니다

### 실습 00. Load dataset

과제를 수행하기 위해 과제파일과 함께 breast data, target을 다운받아 불러옵니다

불러온 dataset은 Wisconsin에서 수집된 breast cancer dataset입니다

target이 0인 경우 negative이고, 1인경우 positive를 의미합니다

해당 데이터셋은 machine learning dataset repository중 하나인 UCI repository에 등록되어있습니다

Raw dataset을 가공하여 csv로 저장하였기 때문에 pandas로 불러올 수 있습니다

In [2]:
import pandas as pd
import os 
import numpy as np

In [3]:
data_path = "C:\\ML\\week03\\breast-data.csv"
target_path = "C:\\ML\\week03\\breast-target.csv"

In [4]:
data=pd.read_csv(data_path)
target=pd.read_csv(target_path)
data.head()

1  2  3  4  5   6  7  8  9
0  5  1  1  1  2   1  3  1  1
1  5  4  4  5  7  10  3  2  1
2  3  1  1  1  2   2  3  1  1
3  6  8  8  1  3   4  3  7  1
4  4  1  1  3  2   1  3  1  1

### 실습 01. Pandas & numpy 사용하기

데이터들을 불러오고 형태를 확인해주세요

DataFrame.shape으로 확인할 수 있습니다

이후, 변수의 갯수와 변수 별 평균, 표준편차를 출력해주세요

출력 양식은 자유롭게 작성하시되, 반드시 위의 요구사항을 만족하여야합니다

In [5]:
df = pd.DataFrame(data)
df.shape

(683, 9)

In [6]:
col = len(df.columns)
print("변수의 갯수 : {}".format(col))

변수의 갯수 : 9


In [7]:
df1 = pd.DataFrame(df.mean())
df2 = pd.DataFrame(df.std())
df3 = np.hstack((df1,df2))
su = pd.DataFrame(df3, columns=["변수의 평균","변수의 표준편차"])
su

변수의 평균  변수의 표준편차
0  4.442167  2.820761
1  3.150805  3.065145
2  3.215227  2.988581
3  2.830161  2.864562
4  3.234261  2.223085
5  3.544656  3.643857
6  3.445095  2.449697
7  2.869693  3.052666
8  1.603221  1.732674

### 실습 02. Gaussian Naive Bayes Classifier

Scikit-learn package의 classifier를 불러오겠습니다

In [8]:
from sklearn.naive_bayes import GaussianNB

불러온 class를 적절한 오브젝트에 저장하고, breast data의 prior를 계산하여 입력해주세요

그리고 학습된 모델의 정확도를 출력해주세요

In [12]:
# 조교 영상 
prior=np.eye(2)[target.values.reshape(-1)].mean(0)
print(prior)
model=GaussianNB(priors=prior)
model.fit(data,target.values.reshape(-1))

print(f'정확도 : {(model.predict(data)==target.values.reshape(-1)).mean()*100:.6}%')

[0.65007321 0.34992679]
정확도 : 96.3397%


In [9]:
target = target.iloc[:,-1]
model=GaussianNB(priors=[0.9, 0.1])
model.fit(data, target)

ac = (model.predict(data)==target.values).mean()*100
print("학습된 모델의 정확도 : {}".format(ac))


학습된 모델의 정확도 : 96.04685212298682


### 실습 03. Prior 조절 및 결과 비교하기

실습 2에서 확인한 것과 같이 breast cancer dataset의 prior 비율은 1:1이 아닙니다

prior를 1:1로 조절한 후 조절하기 전과 비교해주세요



In [13]:
equal_model=GaussianNB(priors=[0.5, 0.5])
equal_model.fit(data, target.values.reshape(-1))
print(f'prior를 입력하지 않은 경우의 정확도 : {(model.predict(data)==target.values).mean()*100:.4}%')
print(f'prior를 입력하지 않은 경우 1이라고 예측한 횟수 : {(model.predict(data)).sum()}\n')
print(f'prior를 입력한  경우의 정확도 : {(equal_model.predict(data)==target.values).mean()*100:.4}%')
print(f'prior를 입력한 경우 1이라고 예측한 횟수 : {(equal_model.predict(data)).sum()}')

prior를 입력하지 않은 경우의 정확도 : 96.34%
prior를 입력하지 않은 경우 1이라고 예측한 횟수 : 254

prior를 입력한  경우의 정확도 : 96.34%
prior를 입력한 경우 1이라고 예측한 횟수 : 254


위과 같이 prior에 따라 결과를 얻게된 이유를 **마크다운**으로 아래 서술해주세요

본인의 생각을 자유롭게 작성해주시면 됩니다

아래쪽에 cell을 추가하는 방법은 이 cell의 왼쪽 여백을 클릭하여 파란색 테두리로 강조되는 것을 확인한 후, 

b키를 누르면 아래쪽에 cell이 생성됩니다

아래쪽 cell의 왼쪽 여백을 클릭하여 파란색 테두리 상태일 때 m키를 누르면 markdown으로 작성할 수 있습니다

In [15]:
model.class_prior_

array([0.65007321, 0.34992679])

In [14]:
model.theta_

array([[2.96396396, 1.30630631, 1.41441441, 1.34684685, 2.10810811,
        1.34684685, 2.08333333, 1.26126126, 1.06531532],
       [7.18828452, 6.57740586, 6.56066946, 5.58577406, 5.32635983,
        7.62761506, 5.9748954 , 5.85774059, 2.60251046]])

In [16]:
model.sigma_

array([[ 2.79149421,  0.73050078,  0.91384629,  0.83915674,  0.76759193,
         1.38420178,  1.12593845,  0.90922004,  0.25924744],
       [ 5.91852385,  7.39045186,  6.57267906, 10.17569722,  5.94369848,
         9.67304495,  5.18765429, 11.16804679,  6.54911505]])

모델의 prior는 0.65대 0.35가 나온다. 
나이브 베이직 클레스파이어가 가장 중요하게 여기는 2가지 파라미터, 즉 가우시안 함수를 설명하는 2가지 평균과 분산이 있는데 평균과 분산이 큰차이를 보여서 분류하기가 쉬워진다.

In [ ]:
그만큼 이미 likelyhood자체가 잘 나눠져 있기때문에 prior가 차이를 발생시켜도 
모델을 크게 변화시키지 않았다.
prior를 극단적으로 변화시킬경우 (0.001 : 0.999) 정확도가 떨어진다.